export const projectsList = [
  {
    id: 1,
    img: "https://i.ibb.co/kQ0XVwW/recipe-app-image-jpg.png",
    title: "Recipe App",
    desc: "Aplication that fetches data from API made in React.JS",
    codeUrl: "https://github.com/kolo3133/recipe-app/tree/main",
    demoUrl: "https://kolo3133.github.io/recipe-app/",
    type: "ReactJS",
  },
  {
    id: 2,
    img: "https://i.ibb.co/sjF2qZF/weather-app-img.png",
    title: "Weather App",
    desc: "Aplication that fetches data of the weather from API made in JavaScript",
    codeUrl: "https://github.com/kolo3133/weather_app/tree/main",
    demoUrl: "https://kolo3133.github.io/weather_app/",
    type: "JavaScript",
  },
  {
    id: 3,
    img: "https://i.ibb.co/7yyLfDb/realestateapp.png",
    title: "Real Estate App",
    desc: "App with list of apartments and search filers, all using API and React.JS",
    codeUrl: "https://github.com/kolo3133/realestate-app/tree/main",
    demoUrl: "",
    type: "ReactJS",
  },
  {
    id: 4,
    img: "https://i.ibb.co/Ptrp8n0/movieapp.png",
    title: "Movie-list App",
    desc: "Aplication that fetches trending movies from API, app is able to sort categories, made in React.JS",
    codeUrl: "https://github.com/kolo3133/movie-list-app/tree/main",
    demoUrl: "https://kolo3133.github.io/movie-list-app/",
    type: "ReactJS",
  },
  {
    id: 5,
    img: "https://i.ibb.co/Jrf7svt/snakegame.png",
    title: "Snake Game",
    desc: "Popular snake re-made in JavaScript",
    codeUrl: "https://github.com/kolo3133/fade-snake-game/tree/main",
    demoUrl: "https://kolo3133.github.io/fade-snake-game/",
    type: "JavaScript",
  },
  {
    id: 6,
    img: "https://i.ibb.co/T1Wz7hC/form.png",
    title: "Form Validation",
    desc: "Form validatior made in JavaScript",
    codeUrl: "https://github.com/kolo3133/form_validation",
    demoUrl: "https://kolo3133.github.io/form_validation/",
    type: "JavaScript",
  },
  {
    id: 7,
    img: "https://i.ibb.co/C89PbWb/todo.png",
    title: "TO DO List",
    desc: "Simple todo list with some options to edit tasks made in JavaScript",
    codeUrl: "https://github.com/kolo3133/todo_list",
    demoUrl: "https://kolo3133.github.io/todo_list/",
    type: "JavaScript",
  },
  {
    id: 8,
    img: "https://i.ibb.co/sVC8sJc/lp.png",
    title: "Landing Page",
    desc: "Simple landing page for company",
    codeUrl: "https://github.com/kolo3133/p1_playvid",
    demoUrl: "https://kolo3133.github.io/p1_playvid/",
    type: "JavaScript",
  },
];
